### ISSUE TITLE
Issue tracker is not available

### ISSUE THREAD

**Issue by david50407** [AdminCMD/AdminCMD#3]
When I connected to `bug.admincmd.com`, it shows "Welcome to nginx on Debian!".

Or how can I report a bug?

**Comment by jkmalan** [comment]
At the moment, it seems the server isn't directing properly. You can use GitHub's issue tracker in the meantime. What bug are you experiencing? Name the version of your server, and the version of AdminCMD you are using, as well as posting any links to errors, exceptions, or relevant log messages.
