### ISSUE TITLE
[Request] Plugin compatibility of teleporting

### ISSUE THREAD

**Issue by david50407** [AdminCMD/AdminCMD#6]
On old AdminCMD, provided its own teleport event and detected if it is caused by a plugin, that can prevent other plugin or custom teleports to modify the 'back' record.

I think the new AdminCMD also can provide this feature for plugin compatibility and provide more pluginable.

**Comment by david50407** [comment]
AdminCMD can be split into common part and core part, that common part only provides events, interfaces, etc that dosen't implement the function but can be used in other plugins to intergrate and enhantence with AdminCMD; And the core part keep the most of codes for implementing AdminCMD.
Like Bukkit and CraftBukkit, or DynmapAPI and Dynmap.

**Comment by TheJeterLP** [comment]
Thanks for that, I will look in implementing this
